# Carregando pacotes
library("shiny")
library("shinythemes")
library("plotly")
library("data.table")
library("shinyWidgets")
library("shinydashboard")
library("shinydashboardPlus")
library("forcats")
library("markdown")
library("simulador.fundeb2")
options(scipen=999)

# Carrega dados
load("data/peso.rda")
load("data/dash-alunos.rda")
load("data/dash-complementar.rda")
load("data/dash-simulacao-inicial.rda")
load("data/codigos-ibge.rda")
load("data/dash-entes-inabilitados.rda")